name: multi
description: Aplicativo da multi - Delivery. 

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.3.1
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.10.0  
  flare_splash_screen: ^2.1.2
  flutter_masked_text: ^0.8.0
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_rating_bar: ^1.3.0+1
  flutter_svg: ^0.17.4
  rubber: ^0.3.2
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: any
  intl: any
  numberpicker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/launcher_ico.png"

flutter:
  assets:
    - lib/assets/
    - lib/assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf

  uses-material-design: true
